// One-shot script: regenerate the frozen KAT (Known Answer Test) and
// write the values to api/voice/kat.frozen.ts. The frozen test then
// imports those values and asserts the implementation still produces
// them byte-for-byte.
//
// To regenerate (only if the spec or library changes):
//   npx tsx scripts/voice-kat-gen.ts
//
// Then commit the updated api/voice/kat.frozen.ts and the updated
// docs/voice-test-vectors.md (which mirrors the same values).

import { writeFileSync } from "fs";
import { x25519, ed25519 } from "@noble/curves/ed25519.js";
import { ml_kem768 } from "@noble/post-quantum/ml-kem.js";
import { sha256 } from "@noble/hashes/sha2.js";
import {
  toHex,
  fromHex,
  computeTranscriptHash,
  deriveKexSecret,
  ed25519Sign,
  ed25519Verify,
  offerSignatureInput,
  x25519Shared,
  kemEncapsulate,
  kemDecapsulate,
} from "../api/voice/kex";
import { deriveKeySchedule, computeSafetyNumberDigest } from "../api/voice/keySchedule";
import { renderSafetyNumber } from "../api/voice/safetyNumber";
import { SrtpSession, type RtpHeader } from "../api/voice/srtp";

// ---------- 1. Generate one set of fresh keys ----------
const callerEd = ed25519.keygen();
const callerX  = x25519.keygen();
const callerM  = ml_kem768.keygen();
const calleeEd = ed25519.keygen();
const calleeX  = x25519.keygen();
const calleeM  = ml_kem768.keygen();
const callerEphX = x25519.keygen();
const callerEphM = ml_kem768.keygen();
const calleeEphX = x25519.keygen();
const calleeEphM = ml_kem768.keygen();

// ---------- 2. KEM encapsulation against CALLER ephemerals ----------
const enc = kemEncapsulate(callerEphM.publicKey);
const mlkemSharedCaller = kemDecapsulate(callerEphM.secretKey, enc.ciphertext);

// ---------- 3. X25519 DH ----------
const xCaller = x25519Shared(callerEphX.secretKey, calleeEphX.publicKey);
const xCallee = x25519Shared(calleeEphX.secretKey, callerEphX.publicKey);

// ---------- 4. Call id (deterministic) ----------
const callId = sha256(fromHex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")).slice(0, 16);

// ---------- 5. Transcript hash ----------
const transcriptHash = computeTranscriptHash({
  callId,
  callerIdentity: { ed25519: callerEd.publicKey, x25519: callerX.publicKey, mlkem: callerM.publicKey },
  calleeIdentity: { ed25519: calleeEd.publicKey, x25519: calleeX.publicKey, mlkem: calleeM.publicKey },
  callerEphemeral: { x25519: callerEphX.publicKey, mlkem: callerEphM.publicKey },
  calleeEphemeralPublic: calleeEphX.publicKey,
  mlkemCiphertext: enc.ciphertext,
});

// ---------- 6. KEX secret ----------
const kexSecret = deriveKexSecret({
  x25519Shared: xCaller,
  mlkemShared: mlkemSharedCaller,
  transcriptHash,
});

// ---------- 7. Key schedule ----------
const schedule = deriveKeySchedule(kexSecret, transcriptHash);

// ---------- 8. Safety number ----------
const safetyDigest = computeSafetyNumberDigest({
  callerIdentity: { x25519: callerX.publicKey, mlkem: callerM.publicKey },
  calleeIdentity: { x25519: calleeX.publicKey, mlkem: calleeM.publicKey },
  safetyNumberSeed: schedule.safetyNumberSeed,
});
const emojiDisplay = renderSafetyNumber(safetyDigest);

// ---------- 9. Offer signature ----------
const sdpCompressed = sha256(new TextEncoder().encode("placeholder SDP body for KAT"));
const offerSigned = offerSignatureInput({
  callId,
  identity: { ed25519: callerEd.publicKey, x25519: callerX.publicKey, mlkem: callerM.publicKey },
  ephemeral: { x25519: callerEphX.publicKey, mlkem: callerEphM.publicKey },
  sdpCompressed,
});
const offerSig = ed25519Sign(callerEd.secretKey, offerSigned);

// ---------- 10. SRTP round-trips ----------
function header(ssrc: number, seq: number, ts: number): RtpHeader {
  return { version: 2, padding: false, extension: false, cc: 0, marker: false, pt: 96, seq, timestamp: ts, ssrc };
}
const srtpSsrc = 0x12345678;
const plaintext = new TextEncoder().encode("Hello SRTP, this is a 100-byte payload that we want to round-trip through SRTP. The payload is longer than one AES block so we exercise the CTR mode across two blocks and ensure no corner case is hit on the block boundary or near the 16-byte counter wraparound point..");

const cmSender = new SrtpSession(srtpSsrc, "AES_CM_128_HMAC_SHA1_80", schedule.srtpMasterKey, schedule.srtpMasterSalt);
const cmPkt = cmSender.encrypt(header(srtpSsrc, 0x0001, 0xCAFEBABE), plaintext);

const gcmSender = new SrtpSession(srtpSsrc, "AES_256_GCM", schedule.srtpGcmKey, schedule.srtpGcmSalt);
const gcmPkt = gcmSender.encrypt(header(srtpSsrc, 0x0001), plaintext);

// ---------- 11. Write the frozen KAT as a TS module ----------
const code = `// AUTO-GENERATED by scripts/voice-kat-gen.ts.
// DO NOT EDIT BY HAND. To regenerate, run: npx tsx scripts/voice-kat-gen.ts
// and commit the updated file.
//
// Library versions: @noble/curves 2.4.0, @noble/post-quantum 0.7.1, @noble/hashes 2.4.0
//
// The values below are deterministic given the inputs: fixed callId, fixed
// identity keys, fixed ephemeral keys, fixed ML-KEM ciphertext. The
// tests/voice.kat.frozen.test.ts test re-derives every output from these
// inputs and asserts byte-for-byte match.

import type { ByteSeq } from "./types";

export const FROZEN_KAT = {
  // Deterministic call id (hash of TEST_SEED truncated to 16 bytes)
  CALL_ID: "${toHex(callId)}",

  // Identity keys (both sides)
  CALLER_ED25519_PUB:  "${toHex(callerEd.publicKey)}",
  CALLER_ED25519_PRIV: "${toHex(callerEd.secretKey)}",
  CALLER_X25519_PUB:   "${toHex(callerX.publicKey)}",
  CALLER_X25519_PRIV:  "${toHex(callerX.secretKey)}",
  CALLER_MLKEM_PUB:    "${toHex(callerM.publicKey)}",
  CALLER_MLKEM_PRIV:   "${toHex(callerM.secretKey)}",
  CALLEE_ED25519_PUB:  "${toHex(calleeEd.publicKey)}",
  CALLEE_ED25519_PRIV: "${toHex(calleeEd.secretKey)}",
  CALLEE_X25519_PUB:   "${toHex(calleeX.publicKey)}",
  CALLEE_X25519_PRIV:  "${toHex(calleeX.secretKey)}",
  CALLEE_MLKEM_PUB:    "${toHex(calleeM.publicKey)}",
  CALLEE_MLKEM_PRIV:   "${toHex(calleeM.secretKey)}",

  // Ephemeral keys (per-call; one-shot in real use)
  CALLER_X25519_EPH_PUB:  "${toHex(callerEphX.publicKey)}",
  CALLER_X25519_EPH_PRIV: "${toHex(callerEphX.secretKey)}",
  CALLER_MLKEM_EPH_PUB:   "${toHex(callerEphM.publicKey)}",
  CALLER_MLKEM_EPH_PRIV:  "${toHex(callerEphM.secretKey)}",
  CALLEE_X25519_EPH_PUB:  "${toHex(calleeEphX.publicKey)}",
  CALLEE_X25519_EPH_PRIV: "${toHex(calleeEphX.secretKey)}",
  CALLEE_MLKEM_EPH_PUB:   "${toHex(calleeEphM.publicKey)}",
  CALLEE_MLKEM_EPH_PRIV:  "${toHex(calleeEphM.secretKey)}",

  // ML-KEM ciphertext (callee encapsulates against caller's ephemeral pub)
  MLKEM_CIPHERTEXT: "${toHex(enc.ciphertext)}",

  // Transcript hash (deterministic from the above)
  TRANSCRIPT_HASH: "${toHex(transcriptHash)}",

  // Shared secrets (32 bytes each)
  X25519_SHARED: "${toHex(xCaller)}",
  MLKEM_SHARED:  "${toHex(mlkemSharedCaller)}",
  KEX_SECRET:    "${toHex(kexSecret)}",

  // Key schedule
  KEX_CHAINING_KEY:   "${toHex(schedule.kexChainingKey)}",
  ROOT_KEY:           "${toHex(schedule.rootKey)}",
  SRTP_MASTER_KEY:    "${toHex(schedule.srtpMasterKey)}",
  SRTP_MASTER_SALT:   "${toHex(schedule.srtpMasterSalt)}",
  SRTP_GCM_KEY:       "${toHex(schedule.srtpGcmKey)}",
  SRTP_GCM_SALT:      "${toHex(schedule.srtpGcmSalt)}",
  RATCHET_ROOT:       "${toHex(schedule.ratchetRoot)}",
  SAFETY_NUMBER_SEED: "${toHex(schedule.safetyNumberSeed)}",

  // Safety number
  SAFETY_NUMBER:  "${toHex(safetyDigest)}",
  EMOJI_DISPLAY:  "${emojiDisplay}",

  // Offer signature (over a placeholder SDP body)
  OFFER_SIGNED_INPUT: "${toHex(offerSigned)}",
  OFFER_SIGNATURE:    "${toHex(offerSig)}",

  // SRTP round-trips (SSRC=0x12345678, seq=0x0001, ts=0xCAFEBABE)
  SRTP_CM_PLAINTEXT:  "${toHex(plaintext)}",
  SRTP_CM_CIPHERTEXT: "${toHex(cmPkt.ciphertext)}",
  SRTP_CM_TAG:        "${toHex(cmPkt.tag)}",
  SRTP_GCM_CIPHERTEXT: "${toHex(gcmPkt.ciphertext)}",
  SRTP_GCM_TAG:        "${toHex(gcmPkt.tag)}",
} as const;

// Convenience: decoded form for tests
export const FROZEN_KAT_BYTES = {
  CALL_ID: FROZEN_KAT.CALL_ID,
  // ... other byte arrays decoded
} as const;
`;

const outPath = new URL("../api/voice/kat.frozen.ts", import.meta.url).pathname;
writeFileSync(outPath, code, "utf8");

console.log(`Wrote ${outPath}`);
console.log("");
console.log("To verify, run: npx vitest run tests/voice.kat.frozen.test.ts");
console.log("Also update docs/voice-test-vectors.md to mirror these values.");
